### ISSUE TITLE
Data conflict at address 00000100

### ISSUE THREAD

**Issue by AtomicRaven** [zznop/ghidra_scripts#2]
Hi ZZNop

When I run GenesisVectorTable.java I am getting the following error:

Error running script: GenesisVectorTable.java
ghidra.program.model.util.CodeUnitInsertionException: Data conflict at address 00000100
ghidra.program.model.util.CodeUnitInsertionException: Data conflict at address 00000100
	at ghidra.program.flatapi.FlatProgramAPI.createAsciiString(FlatProgramAPI.java:1706)
	at GenesisVectorTable.createLabeledStringAndIncrement(GenesisVectorTable.java:51)
	at GenesisVectorTable.createRomHeader(GenesisVectorTable.java:204)
	at GenesisVectorTable.run(GenesisVectorTable.java:266)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:365)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:220)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:198)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:57)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

---------------------------------------------------
Build Date: 2019-Sep-23 1119 EDT
Ghidra Version: 9.1-BETA
Java Home: C:\Program Files\Java\jdk-11.0.5
JVM Version: Oracle Corporation 11.0.5
OS: Windows 10 10.0 amd64
Workstation: host.docker.internal

Thanks, very new to this

**Comment by zznop** [comment]
Hmm was this after a clean import or did you add types manually before running the script? Seems like you already have a type defined at 0x100. Which is causing issues when the script tries to apply a type there.
